FROM ubuntu

# this is a prototype Docker emulation of a Temporal IPFS node

# requirements
RUN apt-get update \
  && apt-get install -y wget \
  && apt-get install -y sudo \
  && rm -rf /var/lib/apt/lists/*

# installation scripts
RUN mkdir -p /install_scripts
COPY scripts/golang_install.sh  /install_scripts/.
COPY scripts/ipfs_install.sh    /install_scripts/.
COPY scripts/cluster_install.sh /install_scripts/.

# boot scripts
RUN mkdir -p /boot_scripts
COPY scripts/temporal_manager.sh    /boot_scripts/.
COPY scripts/temporal_service.sh    /boot_scripts/.
COPY scripts/cluster_manager.sh     /boot_scripts/.
COPY scripts/ipfs_manager_script.sh /boot_scripts/.
RUN chmod u+x -R /boot_scripts/.

# setup
RUN bash /install_scripts/golang_install.sh
RUN bash /install_scripts/ipfs_install.sh
RUN bash /install_scripts/cluster_install.sh

# prepare init
COPY configs/ipfs.service          /etc/systemd/system/.
COPY configs/ipfs_cluster.service  /etc/systemd/system/.

RUN cat /ipfs/config

RUN sudo systemctl start ipfs.service
RUN sudo systemctl start ipfs_cluster.service

CMD ["/usr/sbin/init"]
