// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tier int32

const (
	Tier_FREE    Tier = 0
	Tier_LIGHT   Tier = 1
	Tier_PARTNER Tier = 9
)

var Tier_name = map[int32]string{
	0: "FREE",
	1: "LIGHT",
	9: "PARTNER",
}

var Tier_value = map[string]int32{
	"FREE":    0,
	"LIGHT":   1,
	"PARTNER": 9,
}

func (x Tier) String() string {
	return proto.EnumName(Tier_name, int32(x))
}

func (Tier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type RecoverReq_Type int32

const (
	RecoverReq_USERNAME RecoverReq_Type = 0
	RecoverReq_PASSWORD RecoverReq_Type = 1
)

var RecoverReq_Type_name = map[int32]string{
	0: "USERNAME",
	1: "PASSWORD",
}

var RecoverReq_Type_value = map[string]int32{
	"USERNAME": 0,
	"PASSWORD": 1,
}

func (x RecoverReq_Type) String() string {
	return proto.EnumName(RecoverReq_Type_name, int32(x))
}

func (RecoverReq_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type RegisterReq struct {
	Credentials          *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	EmailAddress         string       `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *RegisterReq) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type RecoverReq struct {
	Type                 RecoverReq_Type `protobuf:"varint,1,opt,name=type,proto3,enum=auth.RecoverReq_Type" json:"type,omitempty"`
	EmailAddress         string          `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecoverReq) Reset()         { *m = RecoverReq{} }
func (m *RecoverReq) String() string { return proto.CompactTextString(m) }
func (*RecoverReq) ProtoMessage()    {}
func (*RecoverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RecoverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverReq.Unmarshal(m, b)
}
func (m *RecoverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverReq.Marshal(b, m, deterministic)
}
func (m *RecoverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverReq.Merge(m, src)
}
func (m *RecoverReq) XXX_Size() int {
	return xxx_messageInfo_RecoverReq.Size(m)
}
func (m *RecoverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverReq proto.InternalMessageInfo

func (m *RecoverReq) GetType() RecoverReq_Type {
	if m != nil {
		return m.Type
	}
	return RecoverReq_USERNAME
}

func (m *RecoverReq) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type UpdateReq struct {
	// Types that are valid to be assigned to Update:
	//	*UpdateReq_PasswordChange
	//	*UpdateReq_TierChange
	Update               isUpdateReq_Update `protobuf_oneof:"update"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

type isUpdateReq_Update interface {
	isUpdateReq_Update()
}

type UpdateReq_PasswordChange struct {
	PasswordChange *UpdateReq_Password `protobuf:"bytes,1,opt,name=password_change,json=passwordChange,proto3,oneof"`
}

type UpdateReq_TierChange struct {
	TierChange *UpdateReq_Tier `protobuf:"bytes,2,opt,name=tier_change,json=tierChange,proto3,oneof"`
}

func (*UpdateReq_PasswordChange) isUpdateReq_Update() {}

func (*UpdateReq_TierChange) isUpdateReq_Update() {}

func (m *UpdateReq) GetUpdate() isUpdateReq_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateReq) GetPasswordChange() *UpdateReq_Password {
	if x, ok := m.GetUpdate().(*UpdateReq_PasswordChange); ok {
		return x.PasswordChange
	}
	return nil
}

func (m *UpdateReq) GetTierChange() *UpdateReq_Tier {
	if x, ok := m.GetUpdate().(*UpdateReq_TierChange); ok {
		return x.TierChange
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpdateReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateReq_PasswordChange)(nil),
		(*UpdateReq_TierChange)(nil),
	}
}

type UpdateReq_Password struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq_Password) Reset()         { *m = UpdateReq_Password{} }
func (m *UpdateReq_Password) String() string { return proto.CompactTextString(m) }
func (*UpdateReq_Password) ProtoMessage()    {}
func (*UpdateReq_Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3, 0}
}

func (m *UpdateReq_Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq_Password.Unmarshal(m, b)
}
func (m *UpdateReq_Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq_Password.Marshal(b, m, deterministic)
}
func (m *UpdateReq_Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq_Password.Merge(m, src)
}
func (m *UpdateReq_Password) XXX_Size() int {
	return xxx_messageInfo_UpdateReq_Password.Size(m)
}
func (m *UpdateReq_Password) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq_Password.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq_Password proto.InternalMessageInfo

func (m *UpdateReq_Password) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UpdateReq_Password) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UpdateReq_Tier struct {
	NewTier              *UpdateReq_Tier `protobuf:"bytes,1,opt,name=new_tier,json=newTier,proto3" json:"new_tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateReq_Tier) Reset()         { *m = UpdateReq_Tier{} }
func (m *UpdateReq_Tier) String() string { return proto.CompactTextString(m) }
func (*UpdateReq_Tier) ProtoMessage()    {}
func (*UpdateReq_Tier) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3, 1}
}

func (m *UpdateReq_Tier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq_Tier.Unmarshal(m, b)
}
func (m *UpdateReq_Tier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq_Tier.Marshal(b, m, deterministic)
}
func (m *UpdateReq_Tier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq_Tier.Merge(m, src)
}
func (m *UpdateReq_Tier) XXX_Size() int {
	return xxx_messageInfo_UpdateReq_Tier.Size(m)
}
func (m *UpdateReq_Tier) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq_Tier.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq_Tier proto.InternalMessageInfo

func (m *UpdateReq_Tier) GetNewTier() *UpdateReq_Tier {
	if m != nil {
		return m.NewTier
	}
	return nil
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Expire               int64    `protobuf:"varint,1,opt,name=expire,proto3" json:"expire,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	EmailAddress string `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	// account properties
	Verified     bool              `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Credits      float64           `protobuf:"fixed64,5,opt,name=credits,proto3" json:"credits,omitempty"`
	IpfsKeys     map[string]string `protobuf:"bytes,6,rep,name=ipfs_keys,json=ipfsKeys,proto3" json:"ipfs_keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IpfsNetworks []string          `protobuf:"bytes,7,rep,name=ipfs_networks,json=ipfsNetworks,proto3" json:"ipfs_networks,omitempty"`
	Tier         Tier              `protobuf:"varint,8,opt,name=tier,proto3,enum=auth.Tier" json:"tier,omitempty"`
	// account access
	ApiAccess            bool     `protobuf:"varint,9,opt,name=api_access,json=apiAccess,proto3" json:"api_access,omitempty"`
	AdminAccess          bool     `protobuf:"varint,10,opt,name=admin_access,json=adminAccess,proto3" json:"admin_access,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetCredits() float64 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func (m *User) GetIpfsKeys() map[string]string {
	if m != nil {
		return m.IpfsKeys
	}
	return nil
}

func (m *User) GetIpfsNetworks() []string {
	if m != nil {
		return m.IpfsNetworks
	}
	return nil
}

func (m *User) GetTier() Tier {
	if m != nil {
		return m.Tier
	}
	return Tier_FREE
}

func (m *User) GetApiAccess() bool {
	if m != nil {
		return m.ApiAccess
	}
	return false
}

func (m *User) GetAdminAccess() bool {
	if m != nil {
		return m.AdminAccess
	}
	return false
}

func init() {
	proto.RegisterEnum("auth.Tier", Tier_name, Tier_value)
	proto.RegisterEnum("auth.RecoverReq_Type", RecoverReq_Type_name, RecoverReq_Type_value)
	proto.RegisterType((*Empty)(nil), "auth.Empty")
	proto.RegisterType((*RegisterReq)(nil), "auth.RegisterReq")
	proto.RegisterType((*RecoverReq)(nil), "auth.RecoverReq")
	proto.RegisterType((*UpdateReq)(nil), "auth.UpdateReq")
	proto.RegisterType((*UpdateReq_Password)(nil), "auth.UpdateReq.Password")
	proto.RegisterType((*UpdateReq_Tier)(nil), "auth.UpdateReq.Tier")
	proto.RegisterType((*Credentials)(nil), "auth.Credentials")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterMapType((map[string]string)(nil), "auth.User.IpfsKeysEntry")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4b, 0x6f, 0xe3, 0x36,
	0x10, 0x8e, 0x64, 0xd9, 0x96, 0x46, 0xd9, 0x44, 0xe1, 0x3e, 0xaa, 0xba, 0x0f, 0xb8, 0xea, 0x25,
	0xed, 0xc1, 0x06, 0x12, 0x2c, 0xb6, 0xe8, 0x13, 0xde, 0xac, 0xdb, 0x2c, 0x9a, 0xa6, 0x01, 0xe3,
	0xa0, 0x47, 0x83, 0xb5, 0x26, 0x0e, 0x11, 0x59, 0x52, 0x49, 0x3a, 0xae, 0x6f, 0x45, 0x6f, 0x3d,
	0x17, 0xbd, 0xf6, 0x4f, 0xf5, 0x2f, 0xf4, 0x87, 0x14, 0x24, 0x25, 0x3f, 0x92, 0x1c, 0x7a, 0xd3,
	0x0c, 0xbf, 0xef, 0x9b, 0x8f, 0xe4, 0x70, 0x04, 0xc0, 0xe6, 0xea, 0xa6, 0x57, 0x8a, 0x42, 0x15,
	0xc4, 0xd3, 0xdf, 0x9d, 0xf7, 0xa7, 0x45, 0x31, 0xcd, 0xb0, 0xcf, 0x4a, 0xde, 0x67, 0x79, 0x5e,
	0x28, 0xa6, 0x78, 0x91, 0x4b, 0x8b, 0x49, 0xda, 0xd0, 0x1c, 0xce, 0x4a, 0xb5, 0x4c, 0xa6, 0x10,
	0x52, 0x9c, 0x72, 0xa9, 0x50, 0x50, 0xfc, 0x85, 0x1c, 0x43, 0x38, 0x11, 0x98, 0x62, 0xae, 0x38,
	0xcb, 0x64, 0xec, 0x74, 0x9d, 0xc3, 0xf0, 0xe8, 0xa0, 0x67, 0xd4, 0x4f, 0xd6, 0x0b, 0x74, 0x13,
	0x45, 0x3e, 0x86, 0x27, 0x38, 0x63, 0x3c, 0x1b, 0xb3, 0x34, 0x15, 0x28, 0x65, 0xec, 0x76, 0x9d,
	0xc3, 0x80, 0xee, 0x9a, 0xe4, 0xc0, 0xe6, 0x92, 0xdf, 0x1c, 0x00, 0x8a, 0x93, 0xe2, 0xce, 0x16,
	0xfa, 0x04, 0x3c, 0xb5, 0x2c, 0xd1, 0x54, 0xd8, 0x3b, 0x7a, 0x6e, 0x2b, 0xac, 0xd7, 0x7b, 0xa3,
	0x65, 0x89, 0xd4, 0x40, 0xfe, 0x9f, 0x7c, 0x02, 0x9e, 0xa6, 0x90, 0x5d, 0xf0, 0xaf, 0x2e, 0x87,
	0xf4, 0x7c, 0xf0, 0xc3, 0x30, 0xda, 0xd1, 0xd1, 0xc5, 0xe0, 0xf2, 0xf2, 0xa7, 0x1f, 0xe9, 0x9b,
	0xc8, 0x49, 0xfe, 0x76, 0x21, 0xb8, 0x2a, 0x53, 0xa6, 0x50, 0x3b, 0x38, 0x81, 0xfd, 0x92, 0x49,
	0xb9, 0x28, 0x44, 0x3a, 0x9e, 0xdc, 0xb0, 0x7c, 0x8a, 0xd5, 0x76, 0x63, 0x6b, 0x66, 0x85, 0xec,
	0x5d, 0x54, 0xb0, 0xd3, 0x1d, 0xba, 0x57, 0x53, 0x4e, 0x0c, 0x83, 0xbc, 0x82, 0x50, 0x71, 0x14,
	0xb5, 0x80, 0x6b, 0x04, 0x9e, 0xdd, 0x17, 0x18, 0x71, 0x14, 0xa7, 0x3b, 0x14, 0x34, 0xd4, 0x12,
	0x3b, 0x17, 0xe0, 0xd7, 0xb2, 0xe4, 0x23, 0xd8, 0x2d, 0xb2, 0x74, 0x5c, 0x4b, 0x1b, 0x1b, 0x01,
	0x0d, 0x8b, 0x2c, 0xdd, 0x84, 0xe4, 0xb8, 0x58, 0x43, 0xec, 0x11, 0x84, 0x39, 0x2e, 0x6a, 0x48,
	0xe7, 0x15, 0x78, 0xba, 0x0e, 0xe9, 0x83, 0xaf, 0xa1, 0xba, 0x56, 0xb5, 0xa1, 0x47, 0xfd, 0xd0,
	0x76, 0x8e, 0x0b, 0xfd, 0xf1, 0xda, 0x87, 0xd6, 0xdc, 0x2c, 0x25, 0x43, 0x08, 0x37, 0x2e, 0x99,
	0x74, 0xc0, 0x9f, 0x4b, 0x14, 0x39, 0x9b, 0x61, 0xe5, 0x69, 0x15, 0xeb, 0xb5, 0x7b, 0x66, 0x56,
	0x71, 0xf2, 0x12, 0x9a, 0xa3, 0xe2, 0x16, 0x73, 0xf2, 0x02, 0x5a, 0xf8, 0x6b, 0xc9, 0x85, 0xa5,
	0x37, 0x68, 0x15, 0x91, 0x67, 0xd0, 0x54, 0x1a, 0x50, 0x31, 0x6d, 0x90, 0xfc, 0xd1, 0x00, 0xef,
	0x4a, 0xa2, 0x20, 0x7b, 0xe0, 0x72, 0x7b, 0x0a, 0x1e, 0x75, 0x79, 0x4a, 0xde, 0x83, 0x40, 0xd7,
	0x1d, 0x1b, 0x23, 0xee, 0xda, 0xc8, 0xb9, 0x36, 0xf2, 0xa0, 0x3b, 0x1a, 0x0f, 0xbb, 0x43, 0xbb,
	0xbd, 0x43, 0xc1, 0xaf, 0x39, 0xa6, 0xb1, 0xd7, 0x75, 0x0e, 0x7d, 0xba, 0x8a, 0x49, 0x0c, 0x6d,
	0xdd, 0xcc, 0x5c, 0xc9, 0xb8, 0xd9, 0x75, 0x0e, 0x1d, 0x5a, 0x87, 0xe4, 0x25, 0x04, 0xbc, 0xbc,
	0x96, 0xe3, 0x5b, 0x5c, 0xca, 0xb8, 0xd5, 0x6d, 0x6c, 0xf4, 0x86, 0x44, 0xd1, 0x7b, 0x5b, 0x5e,
	0xcb, 0xef, 0x71, 0x29, 0x87, 0xb9, 0x12, 0x4b, 0xea, 0xf3, 0x2a, 0xd4, 0x8e, 0x0c, 0x2d, 0x47,
	0xb5, 0x28, 0xc4, 0xad, 0x8c, 0xdb, 0xdd, 0x86, 0x76, 0xa4, 0x93, 0xe7, 0x55, 0x8e, 0x7c, 0x08,
	0x9e, 0xb9, 0x21, 0xdf, 0xf4, 0x3f, 0x58, 0x59, 0x73, 0x2f, 0x26, 0x4f, 0x3e, 0x00, 0x60, 0x25,
	0x1f, 0xb3, 0xc9, 0x44, 0xef, 0x29, 0x30, 0x9e, 0x03, 0x56, 0xf2, 0x81, 0x49, 0xe8, 0x7e, 0x60,
	0xe9, 0x8c, 0xe7, 0x35, 0x00, 0x0c, 0x20, 0x34, 0x39, 0x0b, 0xe9, 0x7c, 0x01, 0x4f, 0xb6, 0x1c,
	0x92, 0x08, 0x1a, 0xb7, 0xb8, 0xac, 0x6e, 0x52, 0x7f, 0xea, 0x7b, 0xb8, 0x63, 0xd9, 0xbc, 0x3e,
	0x54, 0x1b, 0x7c, 0xee, 0x7e, 0xe6, 0x7c, 0xda, 0xab, 0x9a, 0xc9, 0x07, 0xef, 0x5b, 0x3a, 0xd4,
	0x4f, 0x29, 0x80, 0xe6, 0xd9, 0xdb, 0xef, 0x4e, 0x47, 0x91, 0x43, 0x42, 0x68, 0x5f, 0x0c, 0xe8,
	0xe8, 0x7c, 0x48, 0xa3, 0x20, 0xf1, 0x7c, 0x37, 0xf2, 0x8f, 0xfe, 0x6a, 0xc0, 0xee, 0x08, 0x67,
	0x65, 0x21, 0x58, 0x36, 0x98, 0xab, 0x1b, 0xf2, 0x06, 0xfc, 0x7a, 0xae, 0x90, 0x83, 0xfa, 0x75,
	0xaf, 0xe6, 0x4c, 0x07, 0xd6, 0xe7, 0x98, 0xbc, 0xfb, 0xfb, 0x3f, 0xff, 0xfe, 0xe9, 0x3e, 0x4d,
	0x0e, 0xfa, 0x77, 0xc7, 0x7d, 0x9d, 0xee, 0x8b, 0x9a, 0x39, 0x80, 0x76, 0x35, 0x13, 0x48, 0x74,
	0x7f, 0x44, 0x6c, 0x69, 0xc4, 0x46, 0x83, 0x24, 0xd1, 0x86, 0x86, 0xe5, 0x7d, 0x03, 0xcd, 0xb3,
	0x62, 0xca, 0x73, 0xf2, 0x70, 0x8a, 0x75, 0xc2, 0xea, 0xd8, 0x4d, 0xfb, 0xbd, 0x30, 0x12, 0x51,
	0xb2, 0xb7, 0x92, 0xc8, 0x0c, 0xef, 0x4b, 0x68, 0x0f, 0x26, 0x93, 0x62, 0x9e, 0x2b, 0x52, 0xe1,
	0xcd, 0xe4, 0x7c, 0xac, 0x3c, 0x59, 0x97, 0x67, 0x15, 0xe5, 0x6b, 0x68, 0xd9, 0x77, 0x47, 0xf6,
	0xef, 0xbd, 0xc2, 0x2d, 0x81, 0x77, 0x8c, 0xc0, 0x41, 0xb2, 0xbf, 0x12, 0xb0, 0x4f, 0x92, 0x7c,
	0xa5, 0x4f, 0xe0, 0x5a, 0xa0, 0xbc, 0xd9, 0xae, 0xbe, 0x65, 0xfd, 0xb1, 0xdd, 0x1b, 0xce, 0xeb,
	0xe7, 0xf0, 0x74, 0x92, 0x15, 0xf3, 0xb4, 0xa7, 0xaa, 0xcb, 0x31, 0xb4, 0x9f, 0x5b, 0xe6, 0x2f,
	0x70, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0xd0, 0xa9, 0xdf, 0x37, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemporalAuthClient is the client API for TemporalAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemporalAuthClient interface {
	// Register facilitates user creation.
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*User, error)
	// Recover facilitates account recovery.
	Recover(ctx context.Context, in *RecoverReq, opts ...grpc.CallOption) (*User, error)
	// Login accepts credentials and returns a token for use with further requests.
	Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Token, error)
	// Account returns the account associated with an authenticated request.
	Account(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error)
	// Update facilitates modification of the account associated with an
	// authenticated request.
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*User, error)
	// Refresh provides a refreshed token associated with an authenticated request.
	Refresh(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Token, error)
}

type temporalAuthClient struct {
	cc *grpc.ClientConn
}

func NewTemporalAuthClient(cc *grpc.ClientConn) TemporalAuthClient {
	return &temporalAuthClient{cc}
}

func (c *temporalAuthClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.TemporalAuth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalAuthClient) Recover(ctx context.Context, in *RecoverReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.TemporalAuth/Recover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalAuthClient) Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/auth.TemporalAuth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalAuthClient) Account(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.TemporalAuth/Account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalAuthClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.TemporalAuth/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalAuthClient) Refresh(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/auth.TemporalAuth/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalAuthServer is the server API for TemporalAuth service.
type TemporalAuthServer interface {
	// Register facilitates user creation.
	Register(context.Context, *RegisterReq) (*User, error)
	// Recover facilitates account recovery.
	Recover(context.Context, *RecoverReq) (*User, error)
	// Login accepts credentials and returns a token for use with further requests.
	Login(context.Context, *Credentials) (*Token, error)
	// Account returns the account associated with an authenticated request.
	Account(context.Context, *Empty) (*User, error)
	// Update facilitates modification of the account associated with an
	// authenticated request.
	Update(context.Context, *UpdateReq) (*User, error)
	// Refresh provides a refreshed token associated with an authenticated request.
	Refresh(context.Context, *Empty) (*Token, error)
}

func RegisterTemporalAuthServer(s *grpc.Server, srv TemporalAuthServer) {
	s.RegisterService(&_TemporalAuth_serviceDesc, srv)
}

func _TemporalAuth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalAuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.TemporalAuth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalAuthServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalAuth_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalAuthServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.TemporalAuth/Recover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalAuthServer).Recover(ctx, req.(*RecoverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.TemporalAuth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalAuthServer).Login(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalAuth_Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalAuthServer).Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.TemporalAuth/Account",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalAuthServer).Account(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalAuth_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalAuthServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.TemporalAuth/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalAuthServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalAuth_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalAuthServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.TemporalAuth/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalAuthServer).Refresh(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemporalAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.TemporalAuth",
	HandlerType: (*TemporalAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TemporalAuth_Register_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _TemporalAuth_Recover_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _TemporalAuth_Login_Handler,
		},
		{
			MethodName: "Account",
			Handler:    _TemporalAuth_Account_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TemporalAuth_Update_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _TemporalAuth_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
