// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/store.proto

package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_140c4391bffcad76, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "store.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemporalStoreClient is the client API for TemporalStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemporalStoreClient interface {
	Status(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type temporalStoreClient struct {
	cc *grpc.ClientConn
}

func NewTemporalStoreClient(cc *grpc.ClientConn) TemporalStoreClient {
	return &temporalStoreClient{cc}
}

func (c *temporalStoreClient) Status(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/store.TemporalStore/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalStoreServer is the server API for TemporalStore service.
type TemporalStoreServer interface {
	Status(context.Context, *Message) (*Message, error)
}

func RegisterTemporalStoreServer(s *grpc.Server, srv TemporalStoreServer) {
	s.RegisterService(&_TemporalStore_serviceDesc, srv)
}

func _TemporalStore_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalStoreServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.TemporalStore/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalStoreServer).Status(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemporalStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.TemporalStore",
	HandlerType: (*TemporalStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _TemporalStore_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store/store.proto",
}

func init() { proto.RegisterFile("store/store.proto", fileDescriptor_store_140c4391bffcad76) }

var fileDescriptor_store_140c4391bffcad76 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2e, 0xc9, 0x2f,
	0x4a, 0xd5, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x94, 0x4c,
	0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62, 0x41, 0xa6, 0x7e, 0x62, 0x5e, 0x5e, 0x7e, 0x49,
	0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x91, 0x92, 0x32, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71,
	0x62, 0x7a, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x2e, 0x84, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0xe3, 0x1a, 0x05, 0x73, 0xf1, 0x86, 0xa4, 0xe6, 0x16, 0xe4, 0x17, 0x25, 0xe6, 0x04, 0x83,
	0xcc, 0x14, 0x72, 0xe2, 0x62, 0x0b, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x16, 0xe2, 0xd3, 0x83, 0x58,
	0x09, 0x35, 0x44, 0x0a, 0x8d, 0xaf, 0x24, 0xd1, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x21, 0x21, 0x01,
	0xfd, 0x32, 0x63, 0x7d, 0x98, 0x1b, 0x41, 0x3a, 0x93, 0xd8, 0xc0, 0x0e, 0x30, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0xb2, 0x7c, 0x16, 0xba, 0x00, 0x00, 0x00,
}
