{
 "title": "Geth-General",
 "time": { "from": "2018-06-08T03:39:44.068Z", "to": "2018-06-08T03:43:20.546Z" },
 "panels": [
  {
   "title": "Eth Chaindata Disk Write Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_eth_db_chaindata_disk_write_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_eth_db_chaindata_disk_write_avgRate05Min",
     "legendFormat": "5min"
    },
    {
     "expr": "geth_eth_db_chaindata_disk_write_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Eth DB Chaindata Disk Read Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_eth_db_chaindata_disk_read_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_eth_db_chaindata_disk_read_avgRate05Min",
     "legendFormat": "5Min"
    },
    {
     "expr": "geth_eth_db_chaindata_disk_read_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Geth Eth State Download Insertion Rate Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_eth_downloader_states_in_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_eth_downloader_states_in_avgRate05Min",
     "legendFormat": "5min"
    },
    {
     "expr": "geth_eth_downloader_states_in_avgRate01Min",
     "legendFormat": "1min"
    }
   ]
  },
  {
   "title": "Eth Header Download Insertion Rate Avg",
   "type": "graph",
   "description": "geth_eth_downloader_headers_in_avgRate15Min",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_eth_downloader_headers_in_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_eth_downloader_headers_in_avgRate05Min",
     "legendFormat": "5min"
    },
    {
     "expr": "geth_eth_downloader_headers_in_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Geth P2P Outbound Traffic Rate Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_p2p_outboundTraffic_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_p2p_outboundTraffic_avgRate05Min",
     "legendFormat": "5Min"
    },
    {
     "expr": "geth_p2p_outboundTraffic_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Geth P2P Inbound Traffic Rate Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_p2p_inboundTraffic_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_p2p_inboundTraffic_avgRate05Min",
     "legendFormat": "5Min"
    },
    {
     "expr": "geth_p2p_inboundTraffic_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Geth V5 Discovery Outbound Traffic Rate Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_discv5_outboundTraffic_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_discv5_outboundTraffic_avgRate05Min",
     "legendFormat": "5Min"
    },
    {
     "expr": "geth_discv5_outboundTraffic_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Geth V5 Discovery Inbound Traffic Rate Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_discv5_inboundTraffic_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_discv5_inboundTraffic_avgRate05Min",
     "legendFormat": "5Min"
    },
    {
     "expr": "geth_discv5_inboundTraffic_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  },
  {
   "title": "Geth System Memory Allocation Rate Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "geth_system_memory_allocs_avgRate15Min",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "15Min",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "geth_system_memory_allocs_avgRate05Min",
     "legendFormat": "5min"
    },
    {
     "expr": "geth_system_memory_allocs_avgRate01Min",
     "legendFormat": "1Min"
    }
   ]
  }
 ]
}