// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipfs/ipfs.proto

package ipfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Key_RSA_Size int32

const (
	Key_RSA_S_2048 Key_RSA_Size = 0
	Key_RSA_S_3072 Key_RSA_Size = 1
	Key_RSA_S_4096 Key_RSA_Size = 2
)

var Key_RSA_Size_name = map[int32]string{
	0: "S_2048",
	1: "S_3072",
	2: "S_4096",
}
var Key_RSA_Size_value = map[string]int32{
	"S_2048": 0,
	"S_3072": 1,
	"S_4096": 2,
}

func (x Key_RSA_Size) String() string {
	return proto.EnumName(Key_RSA_Size_name, int32(x))
}
func (Key_RSA_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{2, 0, 0}
}

type Key_ED25519_Size int32

const (
	Key_ED25519_S_256 Key_ED25519_Size = 0
)

var Key_ED25519_Size_name = map[int32]string{
	0: "S_256",
}
var Key_ED25519_Size_value = map[string]int32{
	"S_256": 0,
}

func (x Key_ED25519_Size) String() string {
	return proto.EnumName(Key_ED25519_Size_name, int32(x))
}
func (Key_ED25519_Size) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{2, 1, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type KeysResp struct {
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysResp) Reset()         { *m = KeysResp{} }
func (m *KeysResp) String() string { return proto.CompactTextString(m) }
func (*KeysResp) ProtoMessage()    {}
func (*KeysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{1}
}
func (m *KeysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysResp.Unmarshal(m, b)
}
func (m *KeysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysResp.Marshal(b, m, deterministic)
}
func (dst *KeysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysResp.Merge(dst, src)
}
func (m *KeysResp) XXX_Size() int {
	return xxx_messageInfo_KeysResp.Size(m)
}
func (m *KeysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysResp.DiscardUnknown(m)
}

var xxx_messageInfo_KeysResp proto.InternalMessageInfo

func (m *KeysResp) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Key struct {
	// Types that are valid to be assigned to Type:
	//	*Key_Rsa
	//	*Key_Ed25519
	Type                 isKey_Type `protobuf_oneof:"type"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string     `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{2}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (dst *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(dst, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

type isKey_Type interface {
	isKey_Type()
}

type Key_Rsa struct {
	Rsa *Key_RSA `protobuf:"bytes,1,opt,name=rsa,proto3,oneof"`
}

type Key_Ed25519 struct {
	Ed25519 *Key_ED25519 `protobuf:"bytes,2,opt,name=ed25519,proto3,oneof"`
}

func (*Key_Rsa) isKey_Type() {}

func (*Key_Ed25519) isKey_Type() {}

func (m *Key) GetType() isKey_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Key) GetRsa() *Key_RSA {
	if x, ok := m.GetType().(*Key_Rsa); ok {
		return x.Rsa
	}
	return nil
}

func (m *Key) GetEd25519() *Key_ED25519 {
	if x, ok := m.GetType().(*Key_Ed25519); ok {
		return x.Ed25519
	}
	return nil
}

func (m *Key) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Key) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Key_OneofMarshaler, _Key_OneofUnmarshaler, _Key_OneofSizer, []interface{}{
		(*Key_Rsa)(nil),
		(*Key_Ed25519)(nil),
	}
}

func _Key_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Key)
	// type
	switch x := m.Type.(type) {
	case *Key_Rsa:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rsa); err != nil {
			return err
		}
	case *Key_Ed25519:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ed25519); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Key.Type has unexpected type %T", x)
	}
	return nil
}

func _Key_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Key)
	switch tag {
	case 1: // type.rsa
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Key_RSA)
		err := b.DecodeMessage(msg)
		m.Type = &Key_Rsa{msg}
		return true, err
	case 2: // type.ed25519
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Key_ED25519)
		err := b.DecodeMessage(msg)
		m.Type = &Key_Ed25519{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Key_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Key)
	// type
	switch x := m.Type.(type) {
	case *Key_Rsa:
		s := proto.Size(x.Rsa)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Key_Ed25519:
		s := proto.Size(x.Ed25519)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Key_RSA struct {
	Size                 Key_RSA_Size `protobuf:"varint,1,opt,name=size,proto3,enum=ipfs.Key_RSA_Size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Key_RSA) Reset()         { *m = Key_RSA{} }
func (m *Key_RSA) String() string { return proto.CompactTextString(m) }
func (*Key_RSA) ProtoMessage()    {}
func (*Key_RSA) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{2, 0}
}
func (m *Key_RSA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_RSA.Unmarshal(m, b)
}
func (m *Key_RSA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_RSA.Marshal(b, m, deterministic)
}
func (dst *Key_RSA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_RSA.Merge(dst, src)
}
func (m *Key_RSA) XXX_Size() int {
	return xxx_messageInfo_Key_RSA.Size(m)
}
func (m *Key_RSA) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_RSA.DiscardUnknown(m)
}

var xxx_messageInfo_Key_RSA proto.InternalMessageInfo

func (m *Key_RSA) GetSize() Key_RSA_Size {
	if m != nil {
		return m.Size
	}
	return Key_RSA_S_2048
}

type Key_ED25519 struct {
	Size                 Key_ED25519_Size `protobuf:"varint,1,opt,name=size,proto3,enum=ipfs.Key_ED25519_Size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Key_ED25519) Reset()         { *m = Key_ED25519{} }
func (m *Key_ED25519) String() string { return proto.CompactTextString(m) }
func (*Key_ED25519) ProtoMessage()    {}
func (*Key_ED25519) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipfs_c0faef59bfce6ebb, []int{2, 1}
}
func (m *Key_ED25519) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_ED25519.Unmarshal(m, b)
}
func (m *Key_ED25519) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_ED25519.Marshal(b, m, deterministic)
}
func (dst *Key_ED25519) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_ED25519.Merge(dst, src)
}
func (m *Key_ED25519) XXX_Size() int {
	return xxx_messageInfo_Key_ED25519.Size(m)
}
func (m *Key_ED25519) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_ED25519.DiscardUnknown(m)
}

var xxx_messageInfo_Key_ED25519 proto.InternalMessageInfo

func (m *Key_ED25519) GetSize() Key_ED25519_Size {
	if m != nil {
		return m.Size
	}
	return Key_ED25519_S_256
}

func init() {
	proto.RegisterType((*Empty)(nil), "ipfs.Empty")
	proto.RegisterType((*KeysResp)(nil), "ipfs.KeysResp")
	proto.RegisterType((*Key)(nil), "ipfs.Key")
	proto.RegisterType((*Key_RSA)(nil), "ipfs.Key.RSA")
	proto.RegisterType((*Key_ED25519)(nil), "ipfs.Key.ED25519")
	proto.RegisterEnum("ipfs.Key_RSA_Size", Key_RSA_Size_name, Key_RSA_Size_value)
	proto.RegisterEnum("ipfs.Key_ED25519_Size", Key_ED25519_Size_name, Key_ED25519_Size_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemporalIPFSClient is the client API for TemporalIPFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemporalIPFSClient interface {
	// Keys returns the IPFS keys associated with an authenticated request.
	Keys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KeysResp, error)
	// NewKey generates a new IPFS key associated with an authenticated request.
	NewKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
}

type temporalIPFSClient struct {
	cc *grpc.ClientConn
}

func NewTemporalIPFSClient(cc *grpc.ClientConn) TemporalIPFSClient {
	return &temporalIPFSClient{cc}
}

func (c *temporalIPFSClient) Keys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KeysResp, error) {
	out := new(KeysResp)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/Keys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) NewKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/NewKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalIPFSServer is the server API for TemporalIPFS service.
type TemporalIPFSServer interface {
	// Keys returns the IPFS keys associated with an authenticated request.
	Keys(context.Context, *Empty) (*KeysResp, error)
	// NewKey generates a new IPFS key associated with an authenticated request.
	NewKey(context.Context, *Key) (*Empty, error)
}

func RegisterTemporalIPFSServer(s *grpc.Server, srv TemporalIPFSServer) {
	s.RegisterService(&_TemporalIPFS_serviceDesc, srv)
}

func _TemporalIPFS_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/Keys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).Keys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_NewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).NewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/NewKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).NewKey(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemporalIPFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipfs.TemporalIPFS",
	HandlerType: (*TemporalIPFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Keys",
			Handler:    _TemporalIPFS_Keys_Handler,
		},
		{
			MethodName: "NewKey",
			Handler:    _TemporalIPFS_NewKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipfs/ipfs.proto",
}

func init() { proto.RegisterFile("ipfs/ipfs.proto", fileDescriptor_ipfs_c0faef59bfce6ebb) }

var fileDescriptor_ipfs_c0faef59bfce6ebb = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0xed, 0x63, 0x28, 0x72, 0x11, 0x28, 0x63, 0x34, 0xb5, 0xd1, 0x04, 0xbb, 0x30, 0x48, 0x62,
	0x8b, 0xc3, 0x43, 0xd1, 0x15, 0x46, 0x0c, 0x86, 0xc4, 0x98, 0xa9, 0x1b, 0x57, 0xa4, 0x86, 0x91,
	0x34, 0x42, 0xdb, 0xd0, 0x46, 0x52, 0x96, 0x6e, 0xfc, 0x00, 0x7f, 0xc2, 0xff, 0xf1, 0x17, 0xfc,
	0x10, 0xd3, 0x01, 0x79, 0xc4, 0xcd, 0xe4, 0xcc, 0xbd, 0xe7, 0x9e, 0x73, 0x73, 0x2e, 0x14, 0xdc,
	0xe0, 0x25, 0xb4, 0x92, 0xc7, 0x0c, 0x26, 0x7e, 0xe4, 0x63, 0x94, 0x60, 0xfd, 0x60, 0xe8, 0xfb,
	0xc3, 0x11, 0xb3, 0x9c, 0xc0, 0xb5, 0x1c, 0xcf, 0xf3, 0x23, 0x27, 0x72, 0x7d, 0x6f, 0xc1, 0x31,
	0xd2, 0x90, 0xea, 0x8c, 0x83, 0x28, 0x36, 0x4e, 0x60, 0xab, 0xc7, 0xe2, 0x90, 0xb2, 0x30, 0xc0,
	0x87, 0x80, 0x5e, 0x59, 0x1c, 0x6a, 0x62, 0x49, 0x2e, 0x67, 0x49, 0xc6, 0xe4, 0x9a, 0x3d, 0x16,
	0x53, 0x5e, 0x36, 0xbe, 0x24, 0x90, 0x7b, 0x2c, 0xc6, 0x47, 0x20, 0x4f, 0x42, 0x47, 0x13, 0x4b,
	0x62, 0x39, 0x4b, 0x72, 0x4b, 0x96, 0x49, 0xed, 0x76, 0x57, 0xa0, 0x49, 0x0f, 0x9f, 0x42, 0x9a,
	0x0d, 0x48, 0xa3, 0x71, 0xd6, 0xd2, 0x24, 0x4e, 0x2b, 0xae, 0x68, 0x9d, 0x1b, 0xde, 0xe8, 0x0a,
	0xf4, 0x8f, 0x83, 0x31, 0x20, 0xcf, 0x19, 0x33, 0x4d, 0x2e, 0x89, 0xe5, 0x0c, 0xe5, 0x18, 0xe7,
	0x41, 0x72, 0x07, 0x1a, 0xe2, 0x15, 0xc9, 0x1d, 0xe8, 0x4f, 0x20, 0x53, 0xbb, 0x8d, 0x8f, 0x01,
	0x85, 0xee, 0x8c, 0x71, 0xf7, 0x3c, 0xc1, 0x1b, 0xee, 0xa6, 0xed, 0xce, 0x18, 0xe5, 0x7d, 0xa3,
	0x02, 0x28, 0xf9, 0x61, 0x00, 0xc5, 0xee, 0x93, 0x6a, 0xfd, 0x42, 0x15, 0xe6, 0xb8, 0x56, 0x3d,
	0x27, 0xaa, 0x38, 0xc7, 0xf5, 0x6a, 0xab, 0xa9, 0x4a, 0x7a, 0x17, 0xd2, 0x8b, 0xa5, 0x70, 0x65,
	0x43, 0x7e, 0xef, 0xdf, 0xd6, 0xeb, 0x16, 0xc5, 0x85, 0x45, 0x06, 0x52, 0x76, 0x9f, 0x34, 0x9a,
	0xaa, 0x70, 0xad, 0x00, 0x8a, 0xe2, 0x80, 0x91, 0x0f, 0x11, 0xb6, 0x1f, 0xd9, 0x38, 0xf0, 0x27,
	0xce, 0xe8, 0xee, 0xe1, 0xd6, 0xc6, 0x97, 0x80, 0x92, 0x98, 0x71, 0x76, 0xae, 0xc8, 0xb3, 0xd7,
	0xf3, 0x4b, 0x79, 0x9e, 0xbf, 0xb1, 0xfb, 0xfe, 0xfd, 0xf3, 0x29, 0x15, 0x70, 0xce, 0x7a, 0xab,
	0xf1, 0x83, 0x5a, 0x49, 0xee, 0xf8, 0x0a, 0x94, 0x7b, 0x36, 0x4d, 0x92, 0x5f, 0x9d, 0x44, 0x5f,
	0x17, 0x32, 0xf6, 0xf9, 0xe0, 0x8e, 0x51, 0xdc, 0x18, 0xb4, 0x3c, 0x36, 0x7d, 0x56, 0xf8, 0xbd,
	0x6b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x7a, 0xc1, 0xca, 0x26, 0x02, 0x00, 0x00,
}
