// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipfs.proto

package ipfs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_faea06b5b3eb1738, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateNetworkReq struct {
	Network              *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	SwarmKey             string   `protobuf:"bytes,2,opt,name=swarm_key,json=swarmKey,proto3" json:"swarm_key,omitempty"`
	BootstrapPeers       []string `protobuf:"bytes,3,rep,name=bootstrap_peers,json=bootstrapPeers,proto3" json:"bootstrap_peers,omitempty"`
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNetworkReq) Reset()         { *m = CreateNetworkReq{} }
func (m *CreateNetworkReq) String() string { return proto.CompactTextString(m) }
func (*CreateNetworkReq) ProtoMessage()    {}
func (*CreateNetworkReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_faea06b5b3eb1738, []int{1}
}

func (m *CreateNetworkReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNetworkReq.Unmarshal(m, b)
}
func (m *CreateNetworkReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNetworkReq.Marshal(b, m, deterministic)
}
func (m *CreateNetworkReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNetworkReq.Merge(m, src)
}
func (m *CreateNetworkReq) XXX_Size() int {
	return xxx_messageInfo_CreateNetworkReq.Size(m)
}
func (m *CreateNetworkReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNetworkReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNetworkReq proto.InternalMessageInfo

func (m *CreateNetworkReq) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *CreateNetworkReq) GetSwarmKey() string {
	if m != nil {
		return m.SwarmKey
	}
	return ""
}

func (m *CreateNetworkReq) GetBootstrapPeers() []string {
	if m != nil {
		return m.BootstrapPeers
	}
	return nil
}

func (m *CreateNetworkReq) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type Network struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_faea06b5b3eb1738, []int{2}
}

func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NetworkList struct {
	Networks             []*Network `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NetworkList) Reset()         { *m = NetworkList{} }
func (m *NetworkList) String() string { return proto.CompactTextString(m) }
func (*NetworkList) ProtoMessage()    {}
func (*NetworkList) Descriptor() ([]byte, []int) {
	return fileDescriptor_faea06b5b3eb1738, []int{3}
}

func (m *NetworkList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkList.Unmarshal(m, b)
}
func (m *NetworkList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkList.Marshal(b, m, deterministic)
}
func (m *NetworkList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkList.Merge(m, src)
}
func (m *NetworkList) XXX_Size() int {
	return xxx_messageInfo_NetworkList.Size(m)
}
func (m *NetworkList) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkList.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkList proto.InternalMessageInfo

func (m *NetworkList) GetNetworks() []*Network {
	if m != nil {
		return m.Networks
	}
	return nil
}

type NetworkDetails struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Activated            int64    `protobuf:"varint,4,opt,name=activated,proto3" json:"activated,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SwarmKey             string   `protobuf:"bytes,6,opt,name=swarm_key,json=swarmKey,proto3" json:"swarm_key,omitempty"`
	Users                []string `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	Peers                []string `protobuf:"bytes,8,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkDetails) Reset()         { *m = NetworkDetails{} }
func (m *NetworkDetails) String() string { return proto.CompactTextString(m) }
func (*NetworkDetails) ProtoMessage()    {}
func (*NetworkDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_faea06b5b3eb1738, []int{4}
}

func (m *NetworkDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkDetails.Unmarshal(m, b)
}
func (m *NetworkDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkDetails.Marshal(b, m, deterministic)
}
func (m *NetworkDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkDetails.Merge(m, src)
}
func (m *NetworkDetails) XXX_Size() int {
	return xxx_messageInfo_NetworkDetails.Size(m)
}
func (m *NetworkDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkDetails.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkDetails proto.InternalMessageInfo

func (m *NetworkDetails) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NetworkDetails) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *NetworkDetails) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *NetworkDetails) GetActivated() int64 {
	if m != nil {
		return m.Activated
	}
	return 0
}

func (m *NetworkDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkDetails) GetSwarmKey() string {
	if m != nil {
		return m.SwarmKey
	}
	return ""
}

func (m *NetworkDetails) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *NetworkDetails) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "ipfs.Empty")
	proto.RegisterType((*CreateNetworkReq)(nil), "ipfs.CreateNetworkReq")
	proto.RegisterType((*Network)(nil), "ipfs.Network")
	proto.RegisterType((*NetworkList)(nil), "ipfs.NetworkList")
	proto.RegisterType((*NetworkDetails)(nil), "ipfs.NetworkDetails")
}

func init() { proto.RegisterFile("ipfs.proto", fileDescriptor_faea06b5b3eb1738) }

var fileDescriptor_faea06b5b3eb1738 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0xe5, 0x5c, 0x9a, 0xf8, 0xe4, 0x52, 0x7a, 0x28, 0xad, 0x09, 0x2d, 0x44, 0xde, 0x34,
	0x6c, 0x62, 0xa9, 0xdd, 0x20, 0xb1, 0x2a, 0x37, 0x29, 0x0a, 0xaa, 0x2a, 0x87, 0x7d, 0x34, 0x4d,
	0xa6, 0x95, 0x55, 0xdb, 0x63, 0x3c, 0x27, 0xa9, 0xb2, 0xe5, 0x15, 0x58, 0xf0, 0x24, 0x3c, 0x09,
	0x2b, 0xf6, 0x3c, 0x08, 0x9a, 0x4b, 0x4c, 0x9d, 0x46, 0x88, 0x05, 0x3b, 0xcf, 0xff, 0x9f, 0xf9,
	0x72, 0xe6, 0x3f, 0x47, 0x01, 0x88, 0xb2, 0x6b, 0x39, 0xcc, 0x72, 0x41, 0x02, 0x6b, 0xea, 0xbb,
	0x77, 0x74, 0x23, 0xc4, 0x4d, 0xcc, 0x03, 0x96, 0x45, 0x01, 0x4b, 0x53, 0x41, 0x8c, 0x22, 0x91,
	0xda, 0x1a, 0xbf, 0x01, 0xf5, 0xf7, 0x49, 0x46, 0x2b, 0xff, 0x9b, 0x03, 0x8f, 0xde, 0xe6, 0x9c,
	0x11, 0xbf, 0xe0, 0x74, 0x27, 0xf2, 0xdb, 0x90, 0x7f, 0xc6, 0x13, 0x68, 0xa4, 0xe6, 0xe4, 0x39,
	0x7d, 0x67, 0xd0, 0x3a, 0xed, 0x0c, 0x35, 0x7f, 0x5d, 0xb2, 0x76, 0xf1, 0x19, 0xb8, 0xf2, 0x8e,
	0xe5, 0xc9, 0xf4, 0x96, 0xaf, 0xbc, 0x4a, 0xdf, 0x19, 0xb8, 0x61, 0x53, 0x0b, 0x63, 0xbe, 0xc2,
	0x13, 0xd8, 0xbd, 0x12, 0x82, 0x24, 0xe5, 0x2c, 0x9b, 0x66, 0x9c, 0xe7, 0xd2, 0xab, 0xf6, 0xab,
	0x03, 0x37, 0xec, 0x16, 0xf2, 0xa5, 0x52, 0x71, 0x1f, 0xea, 0x0b, 0xa9, 0xec, 0x9a, 0xb6, 0xcd,
	0xc1, 0x3f, 0x86, 0x86, 0xfd, 0x3d, 0x44, 0xa8, 0xa5, 0x2c, 0xe1, 0xba, 0x19, 0x37, 0xd4, 0xdf,
	0xfe, 0x2b, 0x68, 0x59, 0xfb, 0x63, 0x24, 0x09, 0x5f, 0x42, 0xd3, 0x36, 0x25, 0x3d, 0xa7, 0x5f,
	0x7d, 0xd8, 0x73, 0x61, 0xfb, 0x3f, 0x1d, 0xe8, 0x5a, 0xf5, 0x1d, 0x27, 0x16, 0xc5, 0x12, 0xbb,
	0x50, 0x89, 0xe6, 0x1a, 0x5f, 0x0f, 0x2b, 0xd1, 0x1c, 0x8f, 0x01, 0x66, 0x3a, 0x94, 0xf9, 0x94,
	0x91, 0x7e, 0x58, 0x35, 0x74, 0xad, 0x72, 0x4e, 0xca, 0x9e, 0xf3, 0x98, 0x5b, 0xbb, 0x6a, 0x6c,
	0xab, 0x9c, 0x13, 0x1e, 0x81, 0xcb, 0x66, 0x14, 0x2d, 0x55, 0xb5, 0x57, 0x33, 0x6e, 0x21, 0x14,
	0x8f, 0xa9, 0xff, 0x79, 0x4c, 0x39, 0xc7, 0x9d, 0x8d, 0x1c, 0x8b, 0x78, 0x1a, 0xf7, 0xe2, 0x51,
	0xaa, 0xc9, 0xb4, 0x69, 0x54, 0x7d, 0x38, 0xfd, 0x5e, 0x83, 0xf6, 0x27, 0x9e, 0x64, 0x22, 0x67,
	0xf1, 0xe8, 0xf2, 0xc3, 0x04, 0x5f, 0xc3, 0xce, 0x84, 0x18, 0x2d, 0x24, 0xb6, 0x4c, 0x1e, 0x7a,
	0xec, 0xbd, 0xfb, 0x07, 0xff, 0xf0, 0xcb, 0x8f, 0x5f, 0x5f, 0x2b, 0x7b, 0xb8, 0x1b, 0x2c, 0xcf,
	0x02, 0xa5, 0x07, 0xd2, 0x5c, 0x99, 0x42, 0xa7, 0xb4, 0x1b, 0x78, 0x60, 0xae, 0x6d, 0x2e, 0x4c,
	0x6f, 0xbf, 0x94, 0xb5, 0x4d, 0xd5, 0xef, 0x6b, 0x6e, 0xcf, 0xf7, 0x0a, 0xee, 0x7a, 0x06, 0x81,
	0xc9, 0x12, 0xc7, 0xd0, 0x9e, 0x10, 0xcb, 0x69, 0xcd, 0x2f, 0xcf, 0xac, 0xdc, 0xe5, 0x0b, 0x4d,
	0x7b, 0xea, 0x1f, 0x3e, 0xa4, 0x49, 0xc5, 0xc0, 0x11, 0xb4, 0x26, 0x24, 0xb2, 0x7f, 0x61, 0x3d,
	0xd7, 0x2c, 0xcf, 0x3f, 0xd8, 0xc6, 0x12, 0x19, 0x8e, 0xa1, 0x13, 0xf2, 0x44, 0x2c, 0xf9, 0xff,
	0x80, 0x85, 0xc5, 0xa6, 0x8e, 0xd2, 0x6b, 0xb1, 0x89, 0xda, 0x1e, 0x9d, 0x65, 0xe2, 0x56, 0x26,
	0x23, 0xbc, 0x80, 0xb6, 0x5a, 0x7b, 0x7b, 0x6b, 0x63, 0xb8, 0x7b, 0x25, 0xa4, 0xaa, 0xfb, 0x5b,
	0x8f, 0x71, 0x24, 0xe9, 0xcd, 0x13, 0x78, 0x3c, 0x8b, 0xc5, 0x62, 0x3e, 0x24, 0xbb, 0x3c, 0x1a,
	0x71, 0xb5, 0xa3, 0xff, 0x2d, 0xce, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xef, 0x68, 0x23,
	0x5f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemporalIPFSClient is the client API for TemporalIPFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemporalIPFSClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	CreateNetwork(ctx context.Context, in *CreateNetworkReq, opts ...grpc.CallOption) (*NetworkDetails, error)
	StartNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*Empty, error)
	StopNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*Empty, error)
	RemoveNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*Empty, error)
	NetworkInfo(ctx context.Context, in *Network, opts ...grpc.CallOption) (*NetworkDetails, error)
	ListNetworks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkList, error)
}

type temporalIPFSClient struct {
	cc *grpc.ClientConn
}

func NewTemporalIPFSClient(cc *grpc.ClientConn) TemporalIPFSClient {
	return &temporalIPFSClient{cc}
}

func (c *temporalIPFSClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) CreateNetwork(ctx context.Context, in *CreateNetworkReq, opts ...grpc.CallOption) (*NetworkDetails, error) {
	out := new(NetworkDetails)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/CreateNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) StartNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/StartNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) StopNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/StopNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) RemoveNetwork(ctx context.Context, in *Network, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/RemoveNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) NetworkInfo(ctx context.Context, in *Network, opts ...grpc.CallOption) (*NetworkDetails, error) {
	out := new(NetworkDetails)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/NetworkInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalIPFSClient) ListNetworks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkList, error) {
	out := new(NetworkList)
	err := c.cc.Invoke(ctx, "/ipfs.TemporalIPFS/ListNetworks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalIPFSServer is the server API for TemporalIPFS service.
type TemporalIPFSServer interface {
	Status(context.Context, *Empty) (*Empty, error)
	CreateNetwork(context.Context, *CreateNetworkReq) (*NetworkDetails, error)
	StartNetwork(context.Context, *Network) (*Empty, error)
	StopNetwork(context.Context, *Network) (*Empty, error)
	RemoveNetwork(context.Context, *Network) (*Empty, error)
	NetworkInfo(context.Context, *Network) (*NetworkDetails, error)
	ListNetworks(context.Context, *Empty) (*NetworkList, error)
}

func RegisterTemporalIPFSServer(s *grpc.Server, srv TemporalIPFSServer) {
	s.RegisterService(&_TemporalIPFS_serviceDesc, srv)
}

func _TemporalIPFS_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/CreateNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).CreateNetwork(ctx, req.(*CreateNetworkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_StartNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Network)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).StartNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/StartNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).StartNetwork(ctx, req.(*Network))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_StopNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Network)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).StopNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/StopNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).StopNetwork(ctx, req.(*Network))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_RemoveNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Network)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).RemoveNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/RemoveNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).RemoveNetwork(ctx, req.(*Network))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_NetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Network)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).NetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/NetworkInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).NetworkInfo(ctx, req.(*Network))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalIPFS_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalIPFSServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs.TemporalIPFS/ListNetworks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalIPFSServer).ListNetworks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemporalIPFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipfs.TemporalIPFS",
	HandlerType: (*TemporalIPFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _TemporalIPFS_Status_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _TemporalIPFS_CreateNetwork_Handler,
		},
		{
			MethodName: "StartNetwork",
			Handler:    _TemporalIPFS_StartNetwork_Handler,
		},
		{
			MethodName: "StopNetwork",
			Handler:    _TemporalIPFS_StopNetwork_Handler,
		},
		{
			MethodName: "RemoveNetwork",
			Handler:    _TemporalIPFS_RemoveNetwork_Handler,
		},
		{
			MethodName: "NetworkInfo",
			Handler:    _TemporalIPFS_NetworkInfo_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _TemporalIPFS_ListNetworks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipfs.proto",
}
